# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/compressMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CompressWidget(object):
    def setupUi(self, CompressWidget):
        CompressWidget.setObjectName("CompressWidget")
        CompressWidget.resize(1000, 700)
        CompressWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(CompressWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minBtn = QtWidgets.QPushButton(CompressWidget)
        self.minBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minBtn.sizePolicy().hasHeightForWidth())
        self.minBtn.setSizePolicy(sizePolicy)
        self.minBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.minBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.minBtn.setStyleSheet("#minBtn{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"}\n"
"#minBtn:hover{\n"
"background-color: #C6C6C6;\n"
"border:none;\n"
"}")
        self.minBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/basic/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minBtn.setIcon(icon)
        self.minBtn.setIconSize(QtCore.QSize(20, 20))
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout.addWidget(self.minBtn)
        self.maxBtn = QtWidgets.QPushButton(CompressWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxBtn.sizePolicy().hasHeightForWidth())
        self.maxBtn.setSizePolicy(sizePolicy)
        self.maxBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.maxBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.maxBtn.setStyleSheet("#maxBtn{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"}\n"
"#maxBtn:hover{\n"
"background-color: #C6C6C6;\n"
"border:none;\n"
"}")
        self.maxBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/basic/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxBtn.setIcon(icon1)
        self.maxBtn.setIconSize(QtCore.QSize(20, 20))
        self.maxBtn.setObjectName("maxBtn")
        self.horizontalLayout.addWidget(self.maxBtn)
        self.closeBtn = QtWidgets.QPushButton(CompressWidget)
        self.closeBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.closeBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.closeBtn.setStyleSheet("#closeBtn{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#closeBtn:hover{\n"
"background-color: #FC6868;\n"
"border:none;\n"
"}")
        self.closeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/basic/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon2)
        self.closeBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(CompressWidget)
        self.widget.setStyleSheet("#widget{background-color: rgb(255,255,255);}\n"
"\n"
".QPushButton{\n"
"    background-color: rgb(245,245,245);\n"
"    border:none;\n"
"    color: rgb(116, 125, 136);\n"
"}\n"
".QPushButton:checked{\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    border:none;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
".QLabel{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("border-bottom:solid;\n"
"border-width:0.5px;\n"
"border-bottom-color: rgb(220, 220, 220);\n"
"background-color: rgb(245,245,245);\n"
"")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(1)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.usageBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usageBtn.sizePolicy().hasHeightForWidth())
        self.usageBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.usageBtn.setFont(font)
        self.usageBtn.setCheckable(True)
        self.usageBtn.setObjectName("usageBtn")
        self.verticalLayout_3.addWidget(self.usageBtn)
        self.pdfBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdfBtn.sizePolicy().hasHeightForWidth())
        self.pdfBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pdfBtn.setFont(font)
        self.pdfBtn.setCheckable(True)
        self.pdfBtn.setObjectName("pdfBtn")
        self.verticalLayout_3.addWidget(self.pdfBtn)
        self.videoBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoBtn.sizePolicy().hasHeightForWidth())
        self.videoBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.videoBtn.setFont(font)
        self.videoBtn.setCheckable(True)
        self.videoBtn.setObjectName("videoBtn")
        self.verticalLayout_3.addWidget(self.videoBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsBtn.sizePolicy().hasHeightForWidth())
        self.settingsBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.settingsBtn.setFont(font)
        self.settingsBtn.setCheckable(True)
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_3.addWidget(self.settingsBtn)
        self.donateBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donateBtn.sizePolicy().hasHeightForWidth())
        self.donateBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.donateBtn.setFont(font)
        self.donateBtn.setCheckable(True)
        self.donateBtn.setObjectName("donateBtn")
        self.verticalLayout_3.addWidget(self.donateBtn)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-top:solid;\n"
"border-width:0.5px;\n"
"border-top-color: rgb(220, 220, 220);\n"
"background-color: rgb(245,245,245);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(CompressWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(CompressWidget)
        QtCore.QMetaObject.connectSlotsByName(CompressWidget)

    def retranslateUi(self, CompressWidget):
        _translate = QtCore.QCoreApplication.translate
        CompressWidget.setWindowTitle(_translate("CompressWidget", "Form"))
        self.label.setText(_translate("CompressWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#931d13;\">江苏省师范生培养信息系统</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">压缩工具</span></p></body></html>"))
        self.usageBtn.setText(_translate("CompressWidget", "使用说明"))
        self.pdfBtn.setText(_translate("CompressWidget", "pdf压缩"))
        self.videoBtn.setText(_translate("CompressWidget", "视频压缩"))
        self.settingsBtn.setText(_translate("CompressWidget", "设置"))
        self.donateBtn.setText(_translate("CompressWidget", "捐赠作者"))
        self.label_2.setText(_translate("CompressWidget", "<html><head/><body><p><br/><span style=\" font-size:10pt; font-weight:600;\">Designed By </span><span style=\" font-size:12pt; font-weight:600; color:#ff5500;\">MoQin </span><img src=\":/logo/github_change.png\" width=\"25\" height=\"25\"/></p><p><span style=\" font-size:10pt; font-weight:600;\">Powered By </span><img src=\":/logo/qt_change.png\" width=\"25\" height=\"25\"/><img src=\":/logo/ffmpeg_change.png\" width=\"25\" height=\"25\"/></p><p height=5px></p></body></html>"))
from img import basicIcon_rc
