# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/compressMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CompressWidget(object):
    def setupUi(self, CompressWidget):
        CompressWidget.setObjectName("CompressWidget")
        CompressWidget.resize(1000, 700)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        CompressWidget.setFont(font)
        CompressWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(CompressWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minBtn = QtWidgets.QPushButton(CompressWidget)
        self.minBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minBtn.sizePolicy().hasHeightForWidth())
        self.minBtn.setSizePolicy(sizePolicy)
        self.minBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.minBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.minBtn.setStyleSheet("#minBtn{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"}\n"
"#minBtn:hover{\n"
"background-color: #C6C6C6;\n"
"border:none;\n"
"}")
        self.minBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/basic/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minBtn.setIcon(icon)
        self.minBtn.setIconSize(QtCore.QSize(20, 20))
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout.addWidget(self.minBtn)
        self.maxBtn = QtWidgets.QPushButton(CompressWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxBtn.sizePolicy().hasHeightForWidth())
        self.maxBtn.setSizePolicy(sizePolicy)
        self.maxBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.maxBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.maxBtn.setStyleSheet("#maxBtn{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"    \n"
"}\n"
"#maxBtn:hover{\n"
"background-color: #C6C6C6;\n"
"border:none;\n"
"}")
        self.maxBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/basic/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxBtn.setIcon(icon1)
        self.maxBtn.setIconSize(QtCore.QSize(20, 20))
        self.maxBtn.setObjectName("maxBtn")
        self.horizontalLayout.addWidget(self.maxBtn)
        self.closeBtn = QtWidgets.QPushButton(CompressWidget)
        self.closeBtn.setMinimumSize(QtCore.QSize(40, 0))
        self.closeBtn.setMaximumSize(QtCore.QSize(50, 25))
        self.closeBtn.setStyleSheet("#closeBtn{\n"
"background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#closeBtn:hover{\n"
"background-color: #FC6868;\n"
"border:none;\n"
"}")
        self.closeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/basic/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon2)
        self.closeBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(CompressWidget)
        self.widget.setStyleSheet("#widget{background-color: rgb(255,255,255);}\n"
"\n"
".QPushButton{\n"
"    background-color: rgb(245,245,245);\n"
"    border:none;\n"
"    color: rgb(116, 125, 136);\n"
"}\n"
".QPushButton:checked{\n"
"    background-color: rgba(255, 255, 255, 255);\n"
"    border:none;\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
".QLabel{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("border-bottom:solid;\n"
"border-width:0.5px;\n"
"border-bottom-color: rgb(220, 220, 220);\n"
"background-color: rgb(245,245,245);\n"
"")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(1)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.usageBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usageBtn.sizePolicy().hasHeightForWidth())
        self.usageBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.usageBtn.setFont(font)
        self.usageBtn.setCheckable(True)
        self.usageBtn.setObjectName("usageBtn")
        self.verticalLayout_3.addWidget(self.usageBtn)
        self.pdfBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pdfBtn.sizePolicy().hasHeightForWidth())
        self.pdfBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.pdfBtn.setFont(font)
        self.pdfBtn.setCheckable(True)
        self.pdfBtn.setObjectName("pdfBtn")
        self.verticalLayout_3.addWidget(self.pdfBtn)
        self.videoBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoBtn.sizePolicy().hasHeightForWidth())
        self.videoBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.videoBtn.setFont(font)
        self.videoBtn.setCheckable(True)
        self.videoBtn.setObjectName("videoBtn")
        self.verticalLayout_3.addWidget(self.videoBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsBtn.sizePolicy().hasHeightForWidth())
        self.settingsBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.settingsBtn.setFont(font)
        self.settingsBtn.setCheckable(True)
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout_3.addWidget(self.settingsBtn)
        self.donateBtn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.donateBtn.sizePolicy().hasHeightForWidth())
        self.donateBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.donateBtn.setFont(font)
        self.donateBtn.setCheckable(True)
        self.donateBtn.setObjectName("donateBtn")
        self.verticalLayout_3.addWidget(self.donateBtn)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-top:solid;\n"
"border-width:0.5px;\n"
"border-top-color: rgb(220, 220, 220);\n"
"background-color: rgb(245,245,245);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.stackedWidget = QtWidgets.QStackedWidget(CompressWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-bottom:solid;\n"
"border-width:0.5px;\n"
"border-bottom-color: rgb(220, 220, 220);\n"
"\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.setStretch(0, 2)
        self.verticalLayout_4.setStretch(1, 13)
        self.stackedWidget.addWidget(self.page)
        self.pdfPage = QtWidgets.QWidget()
        self.pdfPage.setStyleSheet("\n"
".QLineEdit{\n"
"    border:solid;\n"
"    border-color:#DCDCDC;\n"
"    border-width:0.5px;\n"
"    height:32px;\n"
"    border-radius:5px;\n"
"}\n"
".QPushButton{\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    width:72px;\n"
"    height:32px;\n"
"    background-color: rgb(126, 123, 123);\n"
"    color:rgb(255, 255, 255);\n"
"    font-family:\"黑体\";\n"
"    font-weight:bold;\n"
"}\n"
"#browseBtn1:hover{\n"
"    background-color: rgb(39, 39, 39);\n"
"}\n"
"#browseBtn2:hover{\n"
"    background-color: rgb(39, 39, 39);\n"
"}\n"
"#clearBtn1{\n"
"    background-color: rgb(252, 104, 104);\n"
"}\n"
"#clearBtn2{\n"
"    background-color: rgb(252, 104, 104);\n"
"}\n"
"#clearBtn1:hover{\n"
"    background-color: rgb(255, 29, 29);\n"
"}\n"
"#clearBtn2:hover{\n"
"    background-color: rgb(255, 29, 29);\n"
"}")
        self.pdfPage.setObjectName("pdfPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pdfPage)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 11)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.pdfPage)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-bottom:solid;\n"
"border-width:0.5px;\n"
"border-bottom-color: rgb(220, 220, 220);\n"
"\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(64, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setContentsMargins(-1, 11, -1, -1)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.pdfPage)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.widget_2 = QtWidgets.QWidget(self.pdfPage)
        self.widget_2.setStyleSheet(".QWidget{\n"
"    background-color: rgb(241, 241, 241);\n"
"    border-radius:10px;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.browseBtn1 = QtWidgets.QPushButton(self.widget_2)
        self.browseBtn1.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.browseBtn1.setFont(font)
        self.browseBtn1.setStyleSheet("#browseBtn1:hover{\n"
"    background-color: rgb(39, 39, 39);\n"
"}\n"
"#clearBtn1{\n"
"    background-color: rgb(252, 104, 104);\n"
"}")
        self.browseBtn1.setObjectName("browseBtn1")
        self.horizontalLayout_4.addWidget(self.browseBtn1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.clearBtn1 = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearBtn1.sizePolicy().hasHeightForWidth())
        self.clearBtn1.setSizePolicy(sizePolicy)
        self.clearBtn1.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setBold(True)
        font.setWeight(75)
        self.clearBtn1.setFont(font)
        self.clearBtn1.setObjectName("clearBtn1")
        self.horizontalLayout_4.addWidget(self.clearBtn1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.label_6 = QtWidgets.QLabel(self.pdfPage)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.widget_3 = QtWidgets.QWidget(self.pdfPage)
        self.widget_3.setStyleSheet(".QWidget{\n"
"background-color: rgb(241, 241, 241);\n"
"border-radius:10px;\n"
"}\n"
".QLabel{\n"
"background-color: rgb(241, 241, 241);\n"
"border-radius:10px;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.widget_3)
        self.label_19 = QtWidgets.QLabel(self.pdfPage)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.widget_4 = QtWidgets.QWidget(self.pdfPage)
        self.widget_4.setStyleSheet(".QWidget{\n"
"background-color: rgb(241, 241, 241);\n"
"border-radius:10px;}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.browseBtn2 = QtWidgets.QPushButton(self.widget_4)
        self.browseBtn2.setObjectName("browseBtn2")
        self.horizontalLayout_6.addWidget(self.browseBtn2)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.clearBtn2 = QtWidgets.QPushButton(self.widget_4)
        self.clearBtn2.setObjectName("clearBtn2")
        self.horizontalLayout_6.addWidget(self.clearBtn2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_6.addWidget(self.widget_4)
        self.label_20 = QtWidgets.QLabel(self.pdfPage)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_5 = QtWidgets.QWidget(self.pdfPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(400, 0))
        self.widget_5.setStyleSheet(".QWidget{\n"
"background-color: rgb(241, 241, 241);\n"
"border-radius:10px;}\n"
"\n"
".QRadioButton{\n"
"background-color: rgb(241, 241, 241);\n"
"}\n"
"QRadioButton::indicator {width: 24px;height: 24px;border-radius:12px}\n"
"                /*单选框未选中样式*/\n"
"QRadioButton::indicator::unchecked {background-color:#DCDCDC}\n"
"                /*单选框选中样式*/\n"
"QRadioButton::indicator::checked {background-color:#7E7B7B}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem11 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.radioButton = QtWidgets.QRadioButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_8.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_8.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_8.addWidget(self.radioButton_3)
        spacerItem12 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.horizontalLayout_7.addWidget(self.widget_5)
        spacerItem13 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.runCompressBtn = QtWidgets.QPushButton(self.pdfPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runCompressBtn.sizePolicy().hasHeightForWidth())
        self.runCompressBtn.setSizePolicy(sizePolicy)
        self.runCompressBtn.setMinimumSize(QtCore.QSize(160, 0))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.runCompressBtn.setFont(font)
        self.runCompressBtn.setStyleSheet("#runCompressBtn{\n"
"    height:48px;\n"
"}\n"
"#runCompressBtn:hover{\n"
"    \n"
"    background-color: rgb(39, 39, 39);\n"
"}")
        self.runCompressBtn.setObjectName("runCompressBtn")
        self.horizontalLayout_7.addWidget(self.runCompressBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(3, 2)
        self.verticalLayout_6.setStretch(5, 1)
        self.verticalLayout_6.setStretch(7, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        spacerItem14 = QtWidgets.QSpacerItem(64, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.setStretch(0, 3)
        self.verticalLayout_5.setStretch(1, 19)
        self.stackedWidget.addWidget(self.pdfPage)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(CompressWidget)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CompressWidget)

    def retranslateUi(self, CompressWidget):
        _translate = QtCore.QCoreApplication.translate
        CompressWidget.setWindowTitle(_translate("CompressWidget", "Form"))
        self.label.setText(_translate("CompressWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#931d13;\">江苏省师范生培养信息系统</span></p><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">压缩工具</span></p></body></html>"))
        self.usageBtn.setText(_translate("CompressWidget", "使用说明"))
        self.pdfBtn.setText(_translate("CompressWidget", "PDF压缩"))
        self.videoBtn.setText(_translate("CompressWidget", "视频压缩"))
        self.settingsBtn.setText(_translate("CompressWidget", "设       置"))
        self.donateBtn.setText(_translate("CompressWidget", "捐赠作者"))
        self.label_2.setText(_translate("CompressWidget", "<html><head/><body><p align=\"center\"><br/></p><p align=\"center\"><img src=\":/logo/github_change.png\" width=\"25\" height=\"25\"/><a href=\"https://github.com/jimmy-moqin/compressTools\"><span style=\" font-size:10pt; font-weight:600; text-decoration: underline; color:#000000;\"> MoQin 作品</span></a></p><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("CompressWidget", "使用说明"))
        self.label_4.setText(_translate("CompressWidget", "PDF压缩"))
        self.label_5.setText(_translate("CompressWidget", "选择文件"))
        self.browseBtn1.setText(_translate("CompressWidget", "浏览"))
        self.clearBtn1.setText(_translate("CompressWidget", "清除"))
        self.label_6.setText(_translate("CompressWidget", "文件信息"))
        self.label_7.setText(_translate("CompressWidget", "文件名"))
        self.label_8.setText(_translate("CompressWidget", "创建时间"))
        self.label_12.setText(_translate("CompressWidget", "修改时间"))
        self.label_16.setText(_translate("CompressWidget", "TextLabel"))
        self.label_18.setText(_translate("CompressWidget", "TextLabel"))
        self.label_11.setText(_translate("CompressWidget", "页数"))
        self.label_17.setText(_translate("CompressWidget", "TextLabel"))
        self.label_10.setText(_translate("CompressWidget", "类型"))
        self.label_13.setText(_translate("CompressWidget", "TextLabel"))
        self.label_14.setText(_translate("CompressWidget", "TextLabel"))
        self.label_9.setText(_translate("CompressWidget", "文件大小"))
        self.label_15.setText(_translate("CompressWidget", "TextLabel"))
        self.label_19.setText(_translate("CompressWidget", "输出路径"))
        self.browseBtn2.setText(_translate("CompressWidget", "浏览"))
        self.clearBtn2.setText(_translate("CompressWidget", "清除"))
        self.label_20.setText(_translate("CompressWidget", "压缩参数"))
        self.radioButton.setText(_translate("CompressWidget", "低质量"))
        self.radioButton_2.setText(_translate("CompressWidget", "中质量"))
        self.radioButton_3.setText(_translate("CompressWidget", "高质量"))
        self.runCompressBtn.setText(_translate("CompressWidget", "执行压缩"))
from img import basicIcon_rc
