# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/proccessDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 213)
        Dialog.setStyleSheet("#Dialog{\n"
"    background-color: rgb(255, 255, 255);\n"
"border-radius:10px;        \n"
"}\n"
".Widget{\n"
"    border-radius:10px;    \n"
"}\n"
".QPushButton{\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    width:72px;\n"
"    height:32px;\n"
"    background-color: rgb(126, 123, 123);\n"
"    color:rgb(255, 255, 255);\n"
"    font-family:\"黑体\";\n"
"    font-weight:bold;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.tip = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.tip.setFont(font)
        self.tip.setObjectName("tip")
        self.verticalLayout.addWidget(self.tip)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.pb = QtWidgets.QProgressBar(Dialog)
        self.pb.setStyleSheet("QProgressBar {\n"
"    border: 2px solid grey;\n"
"    border-radius: 10px;\n"
"    background-color: #f0f0f0;\n"
"    text-align: center;\n"
"    color:#ffffff #000000;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #373737;\n"
"    width: 20px;\n"
"}")
        self.pb.setProperty("value", 50)
        self.pb.setObjectName("pb")
        self.verticalLayout.addWidget(self.pb)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.finishedPages = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.finishedPages.setFont(font)
        self.finishedPages.setObjectName("finishedPages")
        self.horizontalLayout.addWidget(self.finishedPages)
        self.totalPages = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.totalPages.setFont(font)
        self.totalPages.setObjectName("totalPages")
        self.horizontalLayout.addWidget(self.totalPages)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.okBtn = QtWidgets.QPushButton(Dialog)
        self.okBtn.setStyleSheet("#okBtn:hover{\n"
"    background-color: rgb(39, 39, 39);\n"
"}")
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout_2.addWidget(self.okBtn)
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setStyleSheet("#cancelBtn{\n"
"    background-color: rgb(252, 104, 104);\n"
"}\n"
"#cancelBtn:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout_2.addWidget(self.cancelBtn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "正在压缩..."))
        self.tip.setText(_translate("Dialog", "正在压缩，请稍后..."))
        self.finishedPages.setText(_translate("Dialog", "已完成 00 页"))
        self.totalPages.setText(_translate("Dialog", "共 99 页"))
        self.okBtn.setText(_translate("Dialog", "确认"))
        self.cancelBtn.setText(_translate("Dialog", "取消"))
